/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as RegistrarImport } from './routes/registrar'
import { Route as RegistrantImport } from './routes/registrant'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const RegistrarRoute = RegistrarImport.update({
  id: '/registrar',
  path: '/registrar',
  getParentRoute: () => rootRoute,
} as any)

const RegistrantRoute = RegistrantImport.update({
  id: '/registrant',
  path: '/registrant',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/registrant': {
      id: '/registrant'
      path: '/registrant'
      fullPath: '/registrant'
      preLoaderRoute: typeof RegistrantImport
      parentRoute: typeof rootRoute
    }
    '/registrar': {
      id: '/registrar'
      path: '/registrar'
      fullPath: '/registrar'
      preLoaderRoute: typeof RegistrarImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/registrant': typeof RegistrantRoute
  '/registrar': typeof RegistrarRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/registrant': typeof RegistrantRoute
  '/registrar': typeof RegistrarRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/registrant': typeof RegistrantRoute
  '/registrar': typeof RegistrarRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/registrant' | '/registrar'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/registrant' | '/registrar'
  id: '__root__' | '/' | '/registrant' | '/registrar'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RegistrantRoute: typeof RegistrantRoute
  RegistrarRoute: typeof RegistrarRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RegistrantRoute: RegistrantRoute,
  RegistrarRoute: RegistrarRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/registrant",
        "/registrar"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/registrant": {
      "filePath": "registrant.tsx"
    },
    "/registrar": {
      "filePath": "registrar.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
